name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: goslides
          POSTGRES_PASSWORD: goslides
          POSTGRES_DB: goslides_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        env:
          TEST_DATABASE: postgres://goslides:goslides@localhost:5432/goslides_test?sslmode=disable
          JWT_KEY: 9160b1317993bf4f3de0e825d0ef78af5181ef4f20a1e3c49e55f6974579103d
          ACCESS_TOKEN_DURATION: 1m
          REFRESH_TOKEN_DURATION: 1h
          TEAM_INVITATION_DURATION: 1h
          LIVE_SESSION_MAX_IDLE_DURATION: 1h
        run: go test ./...
